# .coderabbit.yaml
language: "en-US"
reviews:
  profile: "chill"  # or "assertive"
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
